name: Build site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repo under $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install deps
      - name: Install deps
        uses: bahmutov/npm-install@v1
      
      # Set the environment vars
      - name: Set environment
        run: echo "AUTHOR_API_TOKEN"=${{ secrets.AUTHOR_API_TOKEN }} >> $GITHUB_ENV

      # Regenerate and commit the see-also data and check-in.
      - name: Generate see-also data
        run: npm run generate-see-also
      - name: Commit see-also data
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Regenerate see-also data" --allow-empty
          git push origin main

      # Build with 11ty
      - name: Run the build script
        run: npm run build
      
      # Publish to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}