name: Generate PR preview links
on:
  pull_request_target:
    types:
      - opened
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Install the npm dependencies
        uses: bahmutov/npm-install@v1
      - name: Generate description
        run: |
          cd .github/scripts
          token=${{ secrets.GITHUB_TOKEN }} node generate-pr-description.js
