name: Generate PR preview links
on:
  pull_request_target:
    types:
      - opened
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate description
        run: |
          cd .github/scripts
          token=${{ secrets.GITHUB_TOKEN }} node generate-pr-description.js
